#!/bin/bash
#
# Hook script to rebuild the website after a git push
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for an sample, or uncomment the next line (on debian)
#

#
# WARNING: this script needs to be placed into .git/hooks 
#          and be made executable.
#


# after receiving changes, check the current HEAD out
umask 0002
cd $GIT_DIR/..
unset GIT_DIR
git reset --hard

# now we can run any script to update content
# example make-website.sh
source ./build_website.sh
